Update correcting issues with URIs.
x-atlas-consortia/hra-lit pull request #5
Opened 2024-05-29 17:03 UTC by mginda

2024-05-29 17:04 UTC, mginda commented
I've tested the sql queries. IRIs are updated to use "%20" for spaces.

2024-05-29 17:11 UTC, bherr2 requested changes

2024-05-29 17:11 UTC, bherr2 commented on scripts/20-create-internal-blazegraph.sh
> +#run_ndjsonld $DIR/hralit-articles.jsonl  $HRA_LIT
Why are some of these commented out?

2024-05-29 17:11 UTC, bherr2 commented on sql/30-data-modeling-hralit/20-hra_journal_entities_C.sql
> + SELECT DISTINCT 'https://purl.humanatlas.io/graph/hra-lit/v0.6#'::text || a.journal_nlmuniqueid::text AS "@id",
We don't need to add version to identifiers. `https://purl.humanatlas.io/graph/hra-lit/v0.6#` => `https://purl.humanatlas.io/graph/hra-lit#` . This is standard practice for our graphs.

2024-08-22 18:16 UTC, bherr2 approved these changes

2024-08-22 18:16 UTC, merged